// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AllHeader: typeof import('./src/components/common/allHeader.vue')['default']
    AllMenu: typeof import('./src/components/common/allMenu.vue')['default']
    Breadcrumb: typeof import('./src/components/common/breadcrumb.vue')['default']
    Container: typeof import('./src/components/common/container.vue')['default']
    DialogForm: typeof import('./src/components/student/dialogForm.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Form: typeof import('./src/components/login/form.vue')['default']
    PasswdDialog: typeof import('./src/components/user/passwdDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selector: typeof import('./src/components/student/selector.vue')['default']
    UsernameDialog: typeof import('./src/components/user/usernameDialog.vue')['default']
  }
}

export {}
